# Generated by Django 5.0.7 on 2024-10-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contectus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContectUs',
            new_name='ContactUs',
        ),
    ]
