# Generated by Django 5.0.7 on 2024-10-31 22:26

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Larger for detail View', null=True, upload_to='project_posters/'),
        ),
    ]
