# Generated by Django 5.0.7 on 2024-10-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_ceo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceo',
            options={'verbose_name': 'CEO', 'verbose_name_plural': 'CEO'},
        ),
    ]
