# Generated by Django 5.0.7 on 2024-10-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_testimonials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonials',
        ),
    ]
