# Generated by Django 5.0.7 on 2024-10-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, help_text='A small icon: avaiable at FontAwesome', null=True, upload_to='service_thumbnails/icons/'),
        ),
    ]
